### PR TITLE
add downMessage and adjust the number of players

### PR DESCRIPTION
**Pull request by ThunderDry**
plz code-review and consideration :(
thank you

### CODE REVIEW

**Review by acrylic-style — CHANGES_REQUESTED** [review]
can you re-indent the file with 2 spaces?

**Comment by ThunderDry** [comment]
ok, i will try it

**Comment by ThunderDry** [comment]
i think i did it

**Review by acrylic-style — APPROVED** [review]
seems ok

**Comment by acrylic-style** [comment]
merged manually with commit https://github.com/acrylic-style/2b2t.jp-bot/commit/0356c13cb02bca24148525e783da862ab05d61e6 (i wanted to remove `re-indent with 2space` https://github.com/acrylic-style/2b2t.jp-bot/pull/2/commits/5b17631c7b9bf225e126e8e62fd05d30892eb44d)

**Pull request closed without merging**
